### ISSUE TITLE
Compile time parser?

### ISSUE THREAD

**Issue by kamilchm** [loloicci/nimly#56]
Hi,

I'm trying to use `nimly` in macro to parse a string and generate Nim AST, but I get an error when I try to use a generated parser:

```nim
Error: cannot evaluate at compile time: parser
```

The code I use is pretty simple and looks like this:

```nim
variant SomeToken:
  ...

niml lexer[SomeToken]:
  ...

nimy parser[SomeToken]:
  ...

macro fromParsedString(str: untyped) =
  var lex = lexer.newWithString($str)
  parser.init() # <- Error: cannot evaluate at compile time: parser
  let someAst = parser.parse(lex)
```

Is it possibe to use `nimly` generated parser at compile time?
I can prepare a full example code but I want to know if it's not unsupported by the `nimly` design?

**Comment by loloicci** [comment]
Thank you for your question.

It is unsupported now.
But technically, It might be able and I am trying to enable this.
(Although there was a bug in nim compiler to avoid this fix, I confirmed it has been fixed now. Thank you for the opportunity to confirm!)

**Comment by loloicci** [comment]
@kamilchm After merging #60, you can use parsers generated with `nimy` in compile-time.
Note that how to initialize a parser is changed in this update.
This change is going to be included next version after solving #54.

Thank you for reporting!

**Comment by kamilchm** [comment]
Wow, I didn't expect to see it so quickly! Thx. I'll check it this week.

**Comment by loloicci** [comment]
Thanks for the checking!
If you find some problems, please report them.

**Comment by kamilchm** [comment]
I've tested it and it works in compile time now. Thx!
